// A6 — Field-based permutation-group families, Brick 2 of the Stauduhar
// deg ≥ 8 closure: affine groups AGL(d,p), projective actions of GL(d,p),
// and the Möbius/semilinear groups PSL/PGL/PΓL(2,q) on P¹(F_q).
//
// Everything is CONSTRUCTED from field arithmetic at runtime — F_p by
// modular arithmetic, F_q (q = p^e) by polynomial arithmetic modulo an
// irreducible found by exhaustive search and certified with Rabin's
// irreducibility test. No permutation, matrix, or field table is transcribed
// from literature (CLAUDE.md REGOLA 0.1); orders/primitivity are verified
// downstream by BsgsGroup + perm_blocks in the unit tests.
//
// Generation facts used (classical):
//   • SL(d,p) is generated by the elementary transvections I + λE_{ij}
//     [Holt-Eick-O'Brien §7; standard]. With the coordinate d-cycle and the
//     torus diag(γ,1,…,1) (γ a primitive root mod p), ⟨T, C, D⟩ = GL(d,p).
//   • AGL(d,p) = translations ⋊ GL(d,p); GL is transitive on F_p^d \ {0},
//     so one translation plus GL generates all of them.
//   • PGL(2,q) = ⟨x↦x+1, x↦γx, x↦1/x⟩ (Borel + Weyl element, Bruhat);
//     PSL(2,q) = ⟨x↦x+1, x↦γ²x, x↦−1/x⟩ (images of det-1 matrices; the
//     squares of γ span F_q additively, giving the full unipotent group).
//   • PΓL(2,q) = PGL(2,q) ⋊ ⟨Frobenius x↦x^p⟩.

#pragma once

#include "perm_group_internal.hpp"

#include "cas/result.hpp"

#include <cstddef>
#include <cstdint>
#include <vector>

namespace cas::algebra::permgrp {

// ---- prime-field linear/affine/projective families ----

// Generators of AGL(d,p) acting on the p^d points of F_p^d, encoded as
// v ↦ Σ v_i·p^i. Requires p prime, d ≥ 1, p^d ≤ 255 (Perm image bound).
[[nodiscard]] Result<std::vector<Perm>> agl_gens(std::size_t d,
                                                 std::uint32_t p);

// Generators of the image of GL(d,p) acting on the (p^d−1)/(p−1) points of
// the projective space P^{d−1}(F_p) (i.e. PGL(d,p)), points enumerated as
// the normalised representatives (lowest nonzero coordinate = 1) in
// increasing encoding order. Requires p prime, d ≥ 2, point count ≤ 255.
[[nodiscard]] Result<std::vector<Perm>> projective_gl_gens(std::size_t d,
                                                           std::uint32_t p);

// ---- GF(q) and the degree-(q+1) Möbius/semilinear families ----

// F_q = F_p[x]/(f), q = p^e, elements encoded as Σ c_i·p^i for the
// polynomial Σ c_i x^i (so 0 and 1 encode the field's 0 and 1). Built by
// build_gf; all tables are computed, none transcribed.
struct Gf {
    std::uint32_t p{0U};
    std::size_t e{0U};
    std::uint32_t q{0U};
    std::uint32_t gamma{0U};          // a generator of F_q^* (order q−1)
    std::vector<std::uint32_t> mul;   // mul[a*q+b] = a·b
    std::vector<std::uint32_t> inv;   // inv[a] = a⁻¹ (a ≠ 0); inv[0] unused
    std::vector<std::uint32_t> neg;   // neg[a] = −a
    std::vector<std::uint32_t> frob;  // frob[a] = a^p

    [[nodiscard]] std::uint32_t add(std::uint32_t a, std::uint32_t b) const;
};

// Constructs F_{p^e}. Requires p prime, e ≥ 1, p^e + 1 ≤ 255 (so that the
// P¹ action below stays within the Perm image bound).
[[nodiscard]] Result<Gf> build_gf(std::uint32_t p, std::size_t e);

// Points of P¹(F_q): index i < q is the field element i (the class [i : 1]),
// index q is ∞ = [1 : 0]. Degree of every Perm below is q+1.
[[nodiscard]] std::vector<Perm> pgl2_point_gens(const Gf& gf);
[[nodiscard]] std::vector<Perm> psl2_point_gens(const Gf& gf);
// The Frobenius x ↦ x^p as a point permutation (fixes ∞). Together with
// pgl2_point_gens it generates PΓL(2,q); with psl2_point_gens and the
// multiplication x ↦ γx it yields the index-2 subgroups above PSL(2,q).
[[nodiscard]] Perm frobenius_point_perm(const Gf& gf);
// x ↦ γ·x as a point permutation (fixes 0 and ∞).
[[nodiscard]] Perm gamma_mult_point_perm(const Gf& gf);

}  // namespace cas::algebra::permgrp
