// A6 — Algorithmic permutation-group constructors, Brick 2 of the Stauduhar
// deg ≥ 8 closure.
//
// Every generator set here is DERIVED from mathematical structure (cycle
// shapes, block partitions, Schreier's lemma, subset combinatorics) — no
// permutation is transcribed from literature tables (CLAUDE.md REGOLA 0.1).
// Orders and structural properties are verified downstream by BsgsGroup in
// the unit tests, never assumed.
//
// Generation facts used (classical, cited for auditability):
//   • S_n = ⟨(0 1), (0 1 … n−1)⟩            [Holt-Eick-O'Brien, §2.2]
//   • A_n = ⟨(0 1 2), c⟩ with c the n-cycle (n odd) or the (n−1)-cycle
//     1…n−1 (n even) — both even, classical two-generator set.
//   • S_a ≀ S_b (imprimitive action on ab points, blocks {ja..ja+a−1}) is
//     generated by S_a on block 0 plus S_b permuting the blocks pointwise.
//   • Schreier's lemma: for H ≤ G of finite index with transversal U,
//     H = ⟨ u·g·rep(ug)⁻¹ : u ∈ U, g ∈ gens(G) ⟩ — used for G ∩ A_n.
//
// Field-based families (affine, projective, semilinear) live in
// perm_construct_fields_internal.hpp.

#pragma once

#include "perm_group_internal.hpp"

#include "cas/result.hpp"

#include <cstddef>
#include <cstdint>
#include <vector>

namespace cas::algebra::permgrp {

// Generators of S_n in its natural action (empty for n ≤ 1).
[[nodiscard]] std::vector<Perm> symmetric_gens(std::size_t n);

// Generators of A_n in its natural action (empty for n ≤ 2).
[[nodiscard]] std::vector<Perm> alternating_gens(std::size_t n);

// Generators of the imprimitive wreath product S_a ≀ S_b acting on the
// ab points {0..ab−1} with canonical blocks B_j = {ja, …, ja+a−1}.
// Requires a ≥ 1, b ≥ 1 and ab ≤ 255 (Perm image bound).
[[nodiscard]] Result<std::vector<Perm>> wreath_gens(std::size_t a,
                                                    std::size_t b);

// Generators of G ∩ A_n where G = ⟨gens⟩ ≤ S_n, via Schreier's lemma on the
// parity homomorphism (transversal {e, t}, t = first odd generator). If no
// generator is odd, G ⊆ A_n already and a copy of `gens` is returned.
[[nodiscard]] Result<std::vector<Perm>> even_part_gens(
    std::size_t n, const std::vector<Perm>& gens);

// Induced action of ⟨gens⟩ ≤ S_m on the C(m,k) k-subsets of {0..m−1},
// enumerated in increasing bitmask order (deterministic indexing). Requires
// 1 ≤ k ≤ m−1, m ≤ 20 and C(m,k) ≤ 255 (Perm image bound) — otherwise a
// structured error. k = 1 reproduces the natural action.
[[nodiscard]] Result<std::vector<Perm>> ksubset_action_gens(
    std::size_t m, std::size_t k, const std::vector<Perm>& gens);

// C(m,k) in exact u64 arithmetic (m ≤ 20 so every intermediate fits).
[[nodiscard]] std::uint64_t binomial_u64(std::size_t m, std::size_t k);

}  // namespace cas::algebra::permgrp
