#pragma once
// polynomial_groebner_fglm.hpp
//
// FGLM (Faugère-Gianni-Lazard-Mora 1993) order-conversion algorithm.
// Converts a zero-dimensional Groebner basis from GRevLex to Lex ordering.
//
// All arithmetic is exact (Rational / BigInt). No double/float.

#include "polynomial_groebner_f4.hpp"
#include "cas/rational.hpp"
#include "cas/result.hpp"

#include <vector>

namespace cas::symbolic { class CASContext; }

namespace cas::algebra {

// Enumerate standard monomials (monomial staircase) under GRevLex.
// A monomial m is standard iff no lm(g) divides m for any g in G_grevlex.
// Returns monomials in total-degree-lex order.
// `max_dim` is a safety cap (hardware guard, configurable via ctx.fglm_max_dimension()).
[[nodiscard]] std::vector<Monomial> enumerate_standard_monomials(
    const std::vector<PolyF4>& G_grevlex,
    std::size_t n_vars,
    std::size_t max_dim = 512U);

// Build the D×D multiplication matrix M_{x_{var_index}} in the quotient ring
// Q[x_1..x_n] / I, where the standard monomials form a Q-basis.
// M_xi[j][k] = coefficient of sigma_k in NF(x_i * sigma_j, G_grevlex).
[[nodiscard]] Result<std::vector<std::vector<Rational>>> build_multiplication_matrix(
    const std::vector<PolyF4>& G_grevlex,
    const std::vector<Monomial>& standard_monomials,
    std::size_t var_index,
    MonomialOrder grevlex_order = MonomialOrder::GRevLex);

// Convert a zero-dimensional GRevLex Groebner basis to a Lex Groebner basis
// using the FGLM algorithm (Faugère-Gianni-Lazard-Mora 1993).
//
// Preconditions:
//   - G_grevlex must be a reduced Groebner basis under GRevLex.
//   - The ideal generated by G_grevlex must be zero-dimensional
//     (finitely many common roots in the algebraic closure).
//
// Returns the reduced Lex Groebner basis, or Unimplemented if the ideal
// is not zero-dimensional (detected via dimension exceeding max_dim guard).
[[nodiscard]] Result<std::vector<PolyF4>> fglm_convert(
    const std::vector<PolyF4>& G_grevlex,
    std::size_t n_vars,
    symbolic::CASContext* ctx = nullptr);

} // namespace cas::algebra
