#pragma once

#include "cas/algebra.hpp"
#include "cas/symbolic.hpp"
#include "cas/result.hpp"
#include <vector>
#include <utility>

namespace cas::algebra {

struct BezoutCoeffs {
    MultivariatePolynomial s;
    MultivariatePolynomial t;
};

// Represents an evaluation point for variables y_1...y_n
struct EvaluationPoint {
    std::vector<Symbol> vars;
    std::vector<BigInt> values;
};

// Ideal generated by <y_1 - alpha_1, ..., y_n - alpha_n>
struct Ideal {
    EvaluationPoint point;
    unsigned int degree; // The power k in I^k
};

// F3.1: Linear Hensel step (Multivariate)
[[nodiscard]] Result<std::pair<MultivariatePolynomial, MultivariatePolynomial>> linear_hensel_step(
    const MultivariatePolynomial& f, 
    const MultivariatePolynomial& g0, 
    const MultivariatePolynomial& h0, 
    const BezoutCoeffs& bezout,
    const Ideal& mod_ideal,
    symbolic::CASContext& ctx
);

// F3.1: Complete Multivariate Hensel Lift
[[nodiscard]] Result<std::vector<MultivariatePolynomial>> multivariate_hensel_lift(
    const MultivariatePolynomial& f,
    const std::vector<MultivariatePolynomial>& mod_factors,
    const EvaluationPoint& eval_pt,
    const BigInt& prime,
    symbolic::CASContext& ctx
);

} // namespace cas::algebra
