#!/usr/bin/env python3
"""
generate_golden_dashboard.py — read per-area JSON outputs from golden_runner
and produce test/golden/REPORT.md with a summary table + delta vs previous run.

Usage:
    python3 scripts/generate_golden_dashboard.py \
        --json-dir <build_dir> \
        --output   test/golden/REPORT.md \
        [--prev    test/golden/REPORT.prev.md]

JSON files expected: <json-dir>/golden_<area>.json
Each file has the format:
    {
      "<area>": {
        "pass": N, "fail": M, "skip": K,
        "examples_fail": [...]
      }
    }

The dashboard generator also accepts a single merged JSON file via --merged.
"""

import argparse
import glob
import json
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path


def load_json_dir(json_dir: str) -> dict:
    """Load all golden_*.json files from a directory and merge them."""
    merged = {}
    pattern = os.path.join(json_dir, "golden_*.json")
    files = sorted(glob.glob(pattern))
    if not files:
        print(f"WARN: no golden_*.json files found in {json_dir}", file=sys.stderr)
    for fpath in files:
        try:
            with open(fpath) as f:
                data = json.load(f)
            for area, stats in data.items():
                if area not in merged:
                    merged[area] = {"pass": 0, "fail": 0, "skip": 0, "examples_fail": []}
                merged[area]["pass"] += stats.get("pass", 0)
                merged[area]["fail"] += stats.get("fail", 0)
                merged[area]["skip"] += stats.get("skip", 0)
                merged[area]["examples_fail"].extend(stats.get("examples_fail", []))
        except (json.JSONDecodeError, OSError) as e:
            print(f"WARN: could not load {fpath}: {e}", file=sys.stderr)
    return merged


def load_merged_json(path: str) -> dict:
    """Load a single pre-merged JSON file."""
    with open(path) as f:
        return json.load(f)


def parse_prev_report(prev_path: str) -> dict:
    """
    Extract pass/fail/skip counts from a previous REPORT.md.
    The table format is expected to match the one generated by this script.
    Returns dict: area -> {pass, fail, skip, total, pct}
    """
    prev = {}
    if not prev_path or not os.path.exists(prev_path):
        return prev
    with open(prev_path) as f:
        content = f.read()
    # Find the table section: lines like "| area | N | M | K | T | P% |"
    for line in content.splitlines():
        m = re.match(
            r"\|\s*([^|]+?)\s*\|\s*(\d+)\s*\|\s*(\d+)\s*\|\s*(\d+)\s*\|\s*(\d+)\s*\|\s*([\d.]+)%\s*\|",
            line,
        )
        if m:
            area = m.group(1).strip()
            if area in ("Area", "TOTAL", "---"):
                continue
            prev[area] = {
                "pass": int(m.group(2)),
                "fail": int(m.group(3)),
                "skip": int(m.group(4)),
                "total": int(m.group(5)),
                "pct": float(m.group(6)),
            }
    return prev


def pct(p: int, f: int) -> float:
    """Pass percentage over decided (pass + fail)."""
    decided = p + f
    return (100.0 * p / decided) if decided > 0 else 0.0


def delta_str(curr_pct: float, prev_pct: float | None) -> str:
    if prev_pct is None:
        return "new"
    diff = curr_pct - prev_pct
    if abs(diff) < 0.05:
        return "="
    sign = "+" if diff > 0 else ""
    return f"{sign}{diff:.1f}%"


def generate_report(data: dict, prev: dict, output_path: str) -> None:
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = []
    lines.append("# Golden Test Report — FASE 0.5")
    lines.append(f"\nGenerated: {now}\n")
    lines.append("## Pass-Rate by Area\n")
    lines.append("| Area | Pass | Fail | Skip | Total | Pass% | Delta |")
    lines.append("|------|------|------|------|-------|-------|-------|")

    grand_pass = 0
    grand_fail = 0
    grand_skip = 0

    area_order = [
        "simplify", "factor", "gcd", "integrate", "diff",
        "limit", "solve", "matrix", "series", "special_fn", "bronstein", "unknown",
    ]
    # Ensure all areas appear
    all_areas = area_order + [a for a in sorted(data.keys()) if a not in area_order]
    seen = set()

    for area in all_areas:
        if area in seen or area not in data:
            continue
        seen.add(area)
        st = data[area]
        p, f, s = st.get("pass", 0), st.get("fail", 0), st.get("skip", 0)
        tot = p + f + s
        p_pct = pct(p, f)
        prev_area = prev.get(area)
        prev_pct = prev_area["pct"] if prev_area else None
        d = delta_str(p_pct, prev_pct)
        lines.append(f"| {area:<10} | {p:>4} | {f:>4} | {s:>4} | {tot:>5} | {p_pct:>5.1f}% | {d:>6} |")
        grand_pass += p
        grand_fail += f
        grand_skip += s

    grand_tot = grand_pass + grand_fail + grand_skip
    grand_pct = pct(grand_pass, grand_fail)
    prev_total = prev.get("TOTAL")
    prev_grand_pct = prev_total["pct"] if prev_total else None
    d_grand = delta_str(grand_pct, prev_grand_pct)
    lines.append(f"| {'**TOTAL**':<10} | {grand_pass:>4} | {grand_fail:>4} | {grand_skip:>4} | {grand_tot:>5} | {grand_pct:>5.1f}% | {d_grand:>6} |")

    lines.append("\n## Failure Examples\n")
    any_fails = False
    for area in all_areas:
        if area not in data:
            continue
        examples = data[area].get("examples_fail", [])
        if not examples:
            continue
        any_fails = True
        lines.append(f"### {area}\n")
        for ex in examples[:5]:
            lines.append(f"- `{ex}`")
        lines.append("")

    if not any_fails:
        lines.append("_No failures recorded._\n")

    lines.append("## Notes\n")
    lines.append("- **SKIP**: our CAS returned `Unimplemented`, Maxima output missing/unparseable,")
    lines.append("  or equality check was inconclusive.")
    lines.append("- **Pass%** is computed over decided inputs (pass + fail); SKIP excluded.")
    lines.append("- Delta compares against previous `REPORT.prev.md` (if available).")
    lines.append("- Maxima reference: 5.49.0 (GPL-2.0-only, unmodified).")
    lines.append("- Corpus seed: 280+ inputs across 11 areas.")

    report_text = "\n".join(lines) + "\n"

    # Backup previous report if output already exists
    out = Path(output_path)
    if out.exists():
        prev_backup = out.with_name("REPORT.prev.md")
        out.rename(prev_backup)
        print(f"Backed up previous report to {prev_backup}")

    out.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write(report_text)

    print(f"Report written to {output_path}")
    print(f"Grand total: {grand_pass} pass / {grand_fail} fail / {grand_skip} skip — {grand_pct:.1f}%")


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate golden test dashboard.")
    ap.add_argument("--json-dir", help="Directory containing golden_*.json files")
    ap.add_argument("--merged",   help="Single pre-merged JSON file")
    ap.add_argument("--output",   default="test/golden/REPORT.md",
                    help="Output markdown path (default: test/golden/REPORT.md)")
    ap.add_argument("--prev",     default="test/golden/REPORT.prev.md",
                    help="Previous REPORT.md for delta (default: test/golden/REPORT.prev.md)")
    args = ap.parse_args()

    if args.merged:
        data = load_merged_json(args.merged)
    elif args.json_dir:
        data = load_json_dir(args.json_dir)
    else:
        ap.error("Provide either --json-dir or --merged")
        return

    if not data:
        print("ERROR: no data loaded.", file=sys.stderr)
        sys.exit(1)

    prev = parse_prev_report(args.prev)
    generate_report(data, prev, args.output)


if __name__ == "__main__":
    main()
